const button=document.querySelector('.menu-toggle');const nav=document.querySelector('#navigation');function closeMenu(){button.setAttribute('aria-expanded','false');nav.classList.remove('open');button.setAttribute('aria-label','Apri menu');}button.addEventListener('click',()=>{const open=button.getAttribute('aria-expanded')!=='true';button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'Chiudi menu':'Apri menu');nav.classList.toggle('open',open);});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){closeMenu();button.focus();}});document.addEventListener('click',e=>{if(!e.target.closest('.header'))closeMenu();});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));window.matchMedia('(min-width: 901px)').addEventListener('change',e=>{if(e.matches)closeMenu();});

// Migliorie globali: foglio aggiuntivo, Privacy e contatto WhatsApp.
const extraStyle=document.createElement('link');extraStyle.rel='stylesheet';extraStyle.href='enhancements.css';document.head.appendChild(extraStyle);
const footerBottom=document.querySelector('.footer-bottom');if(footerBottom&&!footerBottom.querySelector('a[href="privacy.html"]')){const privacy=document.createElement('a');privacy.href='privacy.html';privacy.textContent='Privacy';footerBottom.insertBefore(privacy,footerBottom.lastElementChild);}
const whatsappUrl='https://wa.me/393474362346?text=Ciao%20ConsulIT%2C%20avrei%20bisogno%20di%20informazioni.';
const contactDetails=document.querySelector('.contact-details');if(contactDetails&&!contactDetails.querySelector('.whatsapp-contact')){const wa=document.createElement('a');wa.className='whatsapp-contact';wa.href=whatsappUrl;wa.target='_blank';wa.rel='noopener noreferrer';wa.innerHTML='<small>WHATSAPP</small><strong>Scrivimi su WhatsApp</strong><span>Apri la chat ↗</span>';contactDetails.appendChild(wa);}
if(!document.querySelector('.whatsapp-float')){const waFloat=document.createElement('a');waFloat.className='whatsapp-float';waFloat.href=whatsappUrl;waFloat.target='_blank';waFloat.rel='noopener noreferrer';waFloat.setAttribute('aria-label','Scrivi a ConsulIT su WhatsApp');waFloat.innerHTML='<span aria-hidden="true">WA</span><b>WhatsApp</b>';document.body.appendChild(waFloat);}

// Cloudflare Web Analytics: statistiche aggregate, senza cookie di profilazione.
if(!document.querySelector('script[data-cf-beacon]')){const analytics=document.createElement('script');analytics.defer=true;analytics.src='https://static.cloudflareinsights.com/beacon.min.js';analytics.setAttribute('data-cf-beacon','{"token":"5cc62b8aabdb4e7ca2ca5c26fde2233f"}');document.head.appendChild(analytics);}
